//setUp database

//CREATE LOG FILE AND DB_DATA FOLDER
//CREATE DATABASE WITH APPLICATION NAME
//CREATE MONGODB USER
//CREATE DATABASE USER
//Not required as model will create it automatically: CREATE COLLECTION USER WITH A INDEXED EMAIL
